apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
