apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  namespace: default
spec:
  volumeName: kafka-pv
  storageClassName: kafka
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi