apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-service
spec:
  ports:
    - name: client-port
      port: 2181
      targetPort: 2181
    - name: follower-port
      port: 2888
      targetPort: 2888
    - name: election-port
      port: 3888
      targetPort: 3888
    - name: admin-server-port
      port: 8080
      targetPort: 8080
  type: ClusterIP
  clusterIP: None
  selector:
    app: zookeeper
